### PR TITLE
Project problem definition

### PR DESCRIPTION
**Pull request by cartermyers**
Hey guys here is the problem definition (task 1 for the report). Could someone please review this and comment any criticisms or comments or anything? I feel like it is still missing something but I don't know what else to add. After we've edited it, we'll mark it as reviewed and we can merge the PR. Thanks

### CODE REVIEW

**Comment by OHIghNoon** [comment]
I assume this is where you want me to talk through?

**Comment by OHIghNoon** [comment]
If so what I was talking about was that we only referred to textbooks in the first sentence but refer to a multitude of things that could be posted on the website in the second, do you think the first sentence should also include our other posting topics? just a thought

**Comment by cartermyers** [comment]
Yeah I could change some of the structure or stuff similar to that, but you think the overall idea id alright? Like is there any other points I should add?

**Comment by cartermyers** [comment]
What do you think now, Michael?

**Comment by OHIghNoon** [comment]
Yeah looks good

**Comment by cartermyers** [comment]
Cool, I'm going to merge this PR and call this part done.

**Pull request merged**
